"""product organization_id

Revision ID: 27526f3151b8
Revises: a87a40de0943
Create Date: 2026-06-18 14:46:49.341229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27526f3151b8'
down_revision: Union[str, Sequence[str], None] = 'a87a40de0943'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('organization_id', sa.Uuid(as_uuid=False), nullable=True))
    op.create_index(op.f('ix_products_organization_id'), 'products', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'products', 'organizations', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_index(op.f('ix_products_organization_id'), table_name='products')
    op.drop_column('products', 'organization_id')
    # ### end Alembic commands ###
