"""catalog products, product_inventory, delivery_allocations

Revision ID: 9e7035ffcfa1
Revises: 761af34c457a
Create Date: 2026-06-19 14:27:28.882732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9e7035ffcfa1'
down_revision: Union[str, Sequence[str], None] = '761af34c457a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_inventory',
    sa.Column('inventory_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('product_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('received_stock', sa.Integer(), nullable=False),
    sa.Column('current_stock', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('Available', 'Reserved', 'LowStock', 'OutOfStock', 'Archived', name='inventory_status'), nullable=False),
    sa.Column('other_info', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('inventory_id'),
    sa.UniqueConstraint('product_id', 'organization_id', name='uq_inventory_product_org')
    )
    op.create_index(op.f('ix_product_inventory_organization_id'), 'product_inventory', ['organization_id'], unique=False)
    op.create_index(op.f('ix_product_inventory_product_id'), 'product_inventory', ['product_id'], unique=False)
    op.create_table('delivery_allocations',
    sa.Column('allocation_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('inventory_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('delivery_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('expected_quantity', sa.Integer(), nullable=False),
    sa.Column('confirmed_quantity', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('Pending', 'Confirmed', 'Discrepancy', 'Missed', name='allocation_status'), nullable=False),
    sa.ForeignKeyConstraint(['delivery_id'], ['deliveries.id'], ),
    sa.ForeignKeyConstraint(['inventory_id'], ['product_inventory.inventory_id'], ),
    sa.PrimaryKeyConstraint('allocation_id')
    )
    op.create_index(op.f('ix_delivery_allocations_delivery_id'), 'delivery_allocations', ['delivery_id'], unique=False)
    op.create_index(op.f('ix_delivery_allocations_inventory_id'), 'delivery_allocations', ['inventory_id'], unique=False)
    op.drop_index(op.f('ix_delivery_items_delivery_id'), table_name='delivery_items')
    op.drop_table('delivery_items')
    op.drop_table('inventory')
    op.add_column('products', sa.Column('sku', sa.String(length=100), nullable=True))
    op.drop_column('products', 'stocks')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('stocks', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('products', 'sku')
    op.create_table('inventory',
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('inventory_organization_id_fkey')),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], name=op.f('inventory_product_id_fkey')),
    sa.PrimaryKeyConstraint('organization_id', 'product_id', name=op.f('inventory_pkey'))
    )
    op.create_table('delivery_items',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('delivery_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('expected_quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('confirmed_quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('Pending', 'Confirmed', 'Discrepancy', 'Missed', name='delivery_item_status'), autoincrement=False, nullable=False),
    sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['delivery_id'], ['deliveries.id'], name=op.f('delivery_items_delivery_id_fkey')),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], name=op.f('delivery_items_product_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('delivery_items_pkey'))
    )
    op.create_index(op.f('ix_delivery_items_delivery_id'), 'delivery_items', ['delivery_id'], unique=False)
    op.drop_index(op.f('ix_delivery_allocations_inventory_id'), table_name='delivery_allocations')
    op.drop_index(op.f('ix_delivery_allocations_delivery_id'), table_name='delivery_allocations')
    op.drop_table('delivery_allocations')
    op.drop_index(op.f('ix_product_inventory_product_id'), table_name='product_inventory')
    op.drop_index(op.f('ix_product_inventory_organization_id'), table_name='product_inventory')
    op.drop_table('product_inventory')
    # ### end Alembic commands ###
