"""initial schema

Revision ID: a87a40de0943
Revises: 
Create Date: 2026-06-18 12:18:57.531113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a87a40de0943'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drivers',
    sa.Column('driver_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('driver_name', sa.String(length=255), nullable=False),
    sa.Column('mobile', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('other_info', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('driver_id')
    )
    op.create_index(op.f('ix_drivers_mobile'), 'drivers', ['mobile'], unique=True)
    op.create_table('universal_id',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('entity_type', sa.Enum('USER', 'ORG', name='entity_type'), nullable=False),
    sa.Column('entity_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'entity_id', name='uq_universal_entity')
    )
    op.create_index(op.f('ix_universal_id_entity_id'), 'universal_id', ['entity_id'], unique=False)
    op.create_table('organizations',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('universal_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('parent_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('Press', 'Hub', 'DistributionUnit', 'Vendor', name='org_type'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('other_info', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('address_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['universal_id'], ['universal_id.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('universal_id')
    )
    op.create_table('products',
    sa.Column('product_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_by', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('stocks', sa.Integer(), nullable=True),
    sa.Column('short_description', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('other_info', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['universal_id.id'], ),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('vehicles',
    sa.Column('vehicle_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('vehicle_number', sa.String(length=50), nullable=False),
    sa.Column('vehicle_type', sa.String(length=10), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('current_driver', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('other_details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['current_driver'], ['drivers.driver_id'], ),
    sa.PrimaryKeyConstraint('vehicle_id')
    )
    op.create_index(op.f('ix_vehicles_vehicle_number'), 'vehicles', ['vehicle_number'], unique=True)
    op.create_table('deliveries',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('parent_delivery_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('type', sa.Enum('Delivery', 'Handend', name='delivery_type'), nullable=False),
    sa.Column('sender_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('recipient_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('driver_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('vehicle_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('status', sa.Enum('Created', 'Packed', 'Dispatched', 'OutForDelivery', 'Delivered', 'Terminated', name='delivery_status'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sender_address_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('recipient_address_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('sender_address_snapshot', sa.Text(), nullable=True),
    sa.Column('recipient_address_snapshot', sa.Text(), nullable=True),
    sa.Column('planned_duration', sa.Integer(), nullable=True),
    sa.Column('confirmed_by', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('photo_url', sa.String(length=1000), nullable=True),
    sa.Column('has_issue', sa.Boolean(), nullable=False),
    sa.Column('issue_count', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['confirmed_by'], ['universal_id.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['universal_id.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.driver_id'], ),
    sa.ForeignKeyConstraint(['parent_delivery_id'], ['deliveries.id'], ),
    sa.ForeignKeyConstraint(['recipient_address_id'], ['addresses.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['universal_id.id'], ),
    sa.ForeignKeyConstraint(['sender_address_id'], ['addresses.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['universal_id.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.vehicle_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deliveries_created_at'), 'deliveries', ['created_at'], unique=False)
    op.create_index(op.f('ix_deliveries_driver_id'), 'deliveries', ['driver_id'], unique=False)
    op.create_index(op.f('ix_deliveries_recipient_address_id'), 'deliveries', ['recipient_address_id'], unique=False)
    op.create_index(op.f('ix_deliveries_recipient_id'), 'deliveries', ['recipient_id'], unique=False)
    op.create_index(op.f('ix_deliveries_sender_address_id'), 'deliveries', ['sender_address_id'], unique=False)
    op.create_index(op.f('ix_deliveries_sender_id'), 'deliveries', ['sender_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('universal_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('mobile', sa.String(length=50), nullable=True),
    sa.Column('role', sa.Enum('Administrator', 'DistributionManager', 'HubOperator', 'Vendor', name='user_role'), nullable=False),
    sa.Column('other_info', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('address_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['universal_id'], ['universal_id.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('universal_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('delivery_access',
    sa.Column('delivery_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('participant_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('entity_type', sa.Enum('USER', 'ORG', name='access_entity_type'), nullable=False),
    sa.Column('access_level', sa.Enum('READ', 'WRITE', 'CONFIRM', name='access_level'), nullable=False),
    sa.ForeignKeyConstraint(['delivery_id'], ['deliveries.id'], ),
    sa.PrimaryKeyConstraint('delivery_id', 'participant_id')
    )
    op.create_table('delivery_assignments_log',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('action', sa.Enum('DRIVER_ASSIGNED', 'DRIVER_CHANGED', 'DRIVER_REMOVED', 'VEHICLE_ASSIGNED', 'VEHICLE_CHANGED', 'VEHICLE_REMOVED', name='assignment_action'), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('driver_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('vehicle_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('delivery_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['delivery_id'], ['deliveries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_assignments_log_delivery_id'), 'delivery_assignments_log', ['delivery_id'], unique=False)
    op.create_table('delivery_items',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('product_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('delivery_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('expected_quantity', sa.Integer(), nullable=False),
    sa.Column('confirmed_quantity', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('Pending', 'Confirmed', 'Discrepancy', 'Missed', name='delivery_item_status'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['delivery_id'], ['deliveries.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_items_delivery_id'), 'delivery_items', ['delivery_id'], unique=False)
    op.create_table('delivery_logs',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('delivery_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['delivery_id'], ['deliveries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_logs_delivery_id'), 'delivery_logs', ['delivery_id'], unique=False)
    op.create_table('issues',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('delivery_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('assigned_to', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('Open', 'Assigned', 'InProgress', 'Resolved', 'Escalated', name='issue_status'), nullable=False),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_by', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['universal_id.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['universal_id.id'], ),
    sa.ForeignKeyConstraint(['delivery_id'], ['deliveries.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['universal_id.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_issues_created_at'), 'issues', ['created_at'], unique=False)
    op.create_index(op.f('ix_issues_delivery_id'), 'issues', ['delivery_id'], unique=False)
    op.create_table('issue_logs',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('issue_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_issue_logs_issue_id'), 'issue_logs', ['issue_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'CRITICAL', name='notification_severity'), nullable=True),
    sa.Column('recipient_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('issue_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cleared_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['universal_id.id'], ),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_recipient_id'), 'notifications', ['recipient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_recipient_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_issue_logs_issue_id'), table_name='issue_logs')
    op.drop_table('issue_logs')
    op.drop_index(op.f('ix_issues_delivery_id'), table_name='issues')
    op.drop_index(op.f('ix_issues_created_at'), table_name='issues')
    op.drop_table('issues')
    op.drop_index(op.f('ix_delivery_logs_delivery_id'), table_name='delivery_logs')
    op.drop_table('delivery_logs')
    op.drop_index(op.f('ix_delivery_items_delivery_id'), table_name='delivery_items')
    op.drop_table('delivery_items')
    op.drop_index(op.f('ix_delivery_assignments_log_delivery_id'), table_name='delivery_assignments_log')
    op.drop_table('delivery_assignments_log')
    op.drop_table('delivery_access')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_deliveries_sender_id'), table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_sender_address_id'), table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_recipient_id'), table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_recipient_address_id'), table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_driver_id'), table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_created_at'), table_name='deliveries')
    op.drop_table('deliveries')
    op.drop_index(op.f('ix_vehicles_vehicle_number'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_table('products')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_universal_id_entity_id'), table_name='universal_id')
    op.drop_table('universal_id')
    op.drop_index(op.f('ix_drivers_mobile'), table_name='drivers')
    op.drop_table('drivers')
    op.drop_table('addresses')
    # ### end Alembic commands ###
