"""delivery timing columns

Revision ID: f50d49952c28
Revises: 27526f3151b8
Create Date: 2026-06-18 15:53:46.066975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f50d49952c28'
down_revision: Union[str, Sequence[str], None] = '27526f3151b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deliveries', sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('deliveries', sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deliveries', 'delivered_at')
    op.drop_column('deliveries', 'dispatched_at')
    # ### end Alembic commands ###
